#!/bin/sh


savepath=$HOME/Pictures/Screenshots/
filename=$(date +%Y%m%d-%H%M%S.png)

##make sure savepath exists
if [[ ! -f $savepath ]]
then
    mkdir -p $savepath
fi
## identify available screens
screens=$(xrandr --listactivemonitors | cut -d' ' -f6)

## prompt user to select the area
chosen=$(echo -e "Hacksaw\nwhole desktop\n$screens" | dmenu -i -p "Select area to screenshot")

## get the area
case "$chosen" in
    Hacksaw) area=$(hacksaw);;

    "whole desktop") area=None;;

    *) area=$(xrandr | grep "$chosen" | cut -d' ' -f3)
       if [ $area == 'primary' ]
       then
           area=$(xrandr | grep "$chosen" | cut -d' ' -f4)
       fi;;
esac

## take screenshot
file=$savepath/$filename
sleep 0.05
if [ $area = None ]
then
    shotgun $file
else
    shotgun -g $area $file
fi

chosen=$(echo -e "Both\nClipboard\nFile" | dmenu -i -p "Save to:")

case "$chosen" in
    Both) xclip -selection Clipboard -t 'image/png' $file;;
    Clipboard) xclip -selection Clipboard -t 'image/png' $file && rm $file;;
    File) echo Saved to "$file";;
esac
